# theme setting access with theme.xxx
# default language, must in hexo root/_config.yml. used to generate multi-lang sites.
# 1st, generate other lang, change hexo root/_config.yml language order and public_dir
# e.g 
# language = [en, zh]
# public_dir = public/en
# run hexo g to generate english site.
# 2st, generate default lang (zh).
# language change to [zh, en]; public_dir = public;
# run hexo g to generate default language site (zh) 
lang: zh
# script and css
js_css:
- url: //cdn.bootcss.com/jquery/2.2.0/jquery.min.js
- url: //cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css
- url: //cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap-theme.min.css
- url: //cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js
- url: //cdn.bootcss.com/highlight.js/9.2.0/styles/railscasts.min.css
- url: //cdn.bootcss.com/highlight.js/9.2.0/highlight.min.js
- url: //cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.pack.js
- url: //cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.min.css
- url: css/nova.css
#- url: js/script.js
# menu, all menu name must be translated, see language/lang.yml
menu:
- name: home
  url: /
- name: project
  url: /p/
- name: category
  url: /categories/
- name: archive
  url: /archives/
- name: about
  url: /about/
- name: donate
  url: /donate/

# post widgets. see layout/post/widget_xxx.swig
post_widgets:
  - search
  - category
  - tag
  - archive
  - recent
# TODO fetch widgets use ajax, widgets e.g. tag, archive, is sample in all pages.
# used ajax to get widget_xxx contents dynamicly to avoid change all pages.
# 
post_widgets_ajax: true
post_widgets_show_count: true
post_widgets_recent_count: 5

# archive
archive:
  type: yearly #yearly|monthly(defaut) see list_archives options
  order: -1 # 1(asc)|-1(desc) defaut desc
  format: YYYY
  show_count: false # true|false, defaut true
  amount: 5 # amount in post widgets

# toc
toc:
  post: true
  project: true
  page: true
# donate
donate:
  data_url: http://ot.ieclipse.cn/ot/index.php/Home/Donate/index
  
# github
gh:
  source_dir: /p/
  cache_dir: gh_cache
  user: Jamling
  token: 961ebbc13a8917f9bf95da79cb078959a5931e42
  repos: 
    - Android-ORM
    - QuickAF
    - adt-extensions
    - eclipse-explorer
    - hexo-theme-nova
    - jarsigner
 
##评论功能设置,目前支持disqus和duoshuo/uyan,需要在上面的modules中进行要应的设置
# show_count 是否显示文章的评论数量
# short_name 对应的short_name
# 需要的其它参数也可以加在下面,然后自己修改模板来使用.theme.comments.xxxxxx来调用
#
# 
comments:
  uyan:
    su: path #path|source

## 站点分析统计代码功能组件
# 加载在站点的footer位置
analytics:
  # google-analytics UA
  google: true
  baidu: true

ajax_widgets: true

## ICP备案编号
Beian:

rss: atom.xml

