# script and css
js_css:
- url: //cdn.bootcss.com/jquery/2.2.0/jquery.min.js
- url: //cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap.min.css
- url: //cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap-theme.min.css
- url: //cdn.bootcss.com/bootstrap/3.3.6/js/bootstrap.min.js
#- url: //cdn.bootcss.com/bootstrap-material-design/0.5.10/css/bootstrap-material-design.min.css
#- url: //cdn.bootcss.com/bootstrap-material-design/0.5.10/css/ripples.min.css
#- url: //cdn.bootcss.com/bootstrap-material-design/0.5.10/js/material.min.js
#- url: //cdn.bootcss.com/bootstrap-material-design/0.5.10/js/ripples.min.js
- url: //cdn.bootcss.com/sidr/2.2.1/jquery.sidr.min.js
- url: //cdn.bootcss.com/sidr/2.2.1/stylesheets/jquery.sidr.dark.min.css
- url: //cdn.bootcss.com/highlight.js/9.2.0/styles/github.min.css
- url: //cdn.bootcss.com/highlight.js/9.2.0/highlight.min.js
- url: //cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.pack.js
- url: //cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.min.css
- url: //cdn.bootcss.com/fancybox/2.1.5/helpers/jquery.fancybox-buttons.css
- url: //cdn.bootcss.com/fancybox/2.1.5/helpers/jquery.fancybox-buttons.js
- url: css/nova_font.css
- url: css/bs/nova.css
#- url: js/script.js
# menu, all menu name must be translated, see language/lang.yml
menu:
- name: home
  url: /
- name: project
  url: /p/
- name: category
  url: /categories/
- name: archive
  url: /archives/
- name: donate
  url: /donate/
- name: about
  url: /about/

# post widgets. see layout/post/widget_xxx.swig
post_widgets:
#  - search
  - category
  - tag
  - archive
  - recent
# TODO fetch widgets use ajax, widgets e.g. tag, archive, is sample in all pages.
# used ajax to get widget_xxx contents dynamicly to avoid change all pages.
# 
post_widgets_ajax: true
post_widgets_show_count: true
post_widgets_recent_count: 5

# archive
archive:
  type: yearly #yearly|monthly(defaut) see list_archives options
  order: -1 # 1(asc)|-1(desc) defaut desc
  format: YYYY
  show_count: false # true|false, defaut true
  amount: 5 # amount in post widgets

# toc
toc:
  post: true
  project: true
  page: true
# donate
donate:
  data_url: http://ot.ieclipse.cn/ot/index.php/Home/Donate/index
  enable: true # whether enable page donate
  
# github removed see hexo-generator-github.
 
##评论功能设置,目前支持disqus和duoshuo/uyan,需要在上面的modules中进行要应的设置
# show_count 是否显示文章的评论数量
# short_name 对应的short_name
# 需要的其它参数也可以加在下面,然后自己修改模板来使用.theme.comments.xxxxxx来调用
#
# 
comments:
  uyan:
    su: path #path|source
    uid: 2064663

## share
share:
  jiathis:
    uid: 2064663
## 站点分析统计代码功能组件
# 加载在站点的footer位置
analytics:
  # google-analytics UA
  google: true
  baidu: true

rss: atom.xml

# icp
icp: 苏ICP备15019510号

## css
node_sass:
  outputStyle: nested

# grid layout
layout:
  index: # index some to post.
    main: col-sx-12 col-sm-8 col-md-9 col-lg-9
    widgets: col-sx-12 col-sm-4 col-md-3 col-lg-3 hidden-xs
  page: #common page
    main: col-sx-12 col-sm-8 col-md-9 col-lg-9
    toc: col-sx-12 col-sm-4 col-md-3 col-lg-3 hidden-xs
  p: #project
    sidebar: col-sx-12 col-sm-12 col-md-2 col-lg-2
    main: col-sx-12 col-sm-8 col-md-8 col-lg-8
    toc: col-sx-2 col-sm-2 col-md-2 col-lg-2 hidden-xs
  d: #donates
    main: col-sx-12 col-sm-8 col-md-9 col-lg-9
    top: col-sx-6 col-sm-4 col-md-3 col-lg-3

